### ISSUE TITLE
Use pika to export TS, esm and require formats at the same time

### ISSUE THREAD

**Issue by haywirez** [react-spring/cannon-es#11]
More of a note than an issue, but using [pika](https://github.com/pikapkg/pack) instead of / in addition to rollup would allow future-proofing the consumption of the package in several preferred formats, with ESM as the default `dist`:
https://www.pika.dev/blog/introducing-pika-pack/

Don't want to overpromise, but I can take a look later 👍

**Comment by codynova** [comment]
Hey @haywirez, thanks for taking the time to take a look!

Can you expand on what benefits you believe it will bring to the table? At first blush, I'm not too keen on switching the build process. Our current rollup config ships ESM and CJS, and is much more familiar to the majority of developers. Not to mention I know my way around webpack and rollup extremely well, but would need to learn pika.

However I'm open to considering it, and @drcmda may have a different opinion.

**Comment by drcmda** [comment]
im curious as well. rollup is extremely efficient in tree-shaking and flat-bundling. setting it up is easy. this is the first time i have heard of pika. from the intro:

> What about web browsers and bundlers? 

all of them

> Is your package optimized for them? 

yes

> Can users load your package from UNPKG?

yes

> Does it include type definitions for VSCode & TypeScript users? 

yes

> Has it been stripped of all unnecessary files to be as small as possible?

yes

but i guess you could make a pr and we can compare if it's smaller/easier ...

**Comment by haywirez** [comment]
Actually you're right, after a second look I see that you already have all the right dists in `package.json` 😆 So not sure what would the benefit be right now. Perhaps as a simpler config for the future, but not a big win right now — happy to close.

**Comment by codynova** [comment]
@haywirez Thanks for checking it out, we look forward to any future contributions you might bring!
