### ISSUE TITLE
Trimesh element will fall

### ISSUE THREAD

**Issue by amirhosseinak20** [react-spring/cannon-es#31]
Hi, 
I loaded gltf scene then initialized my scene. for adding physics i converted Object3d into cannon with [threeToCannon](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjii8mY-PrpAhUoNOwKHRoRASAQFjAAegQIARAB&url=https%3A%2F%2Fgithub.com%2Fdonmccurdy%2Fthree-to-cannon&usg=AOvVaw2XcksKJT91gLj3SvicNid0), after doing this my pins will fall and pass from the ground like the image bellow 
![Screenshot (105)](https://user-images.githubusercontent.com/44077252/84449645-40f8ac00-ac63-11ea-8d4d-193941d250ab.png)
i checked the position and they are correct.
every thing that isn't a trimesh stays on the ground, but trimesh elements pass th ground and go to the underground

**Comment by codynova** [comment]
Hi @amirhosseinak20, what is your ground surface shape? A Box? `cannon-es` currently only supports Trimesh collisions with Spheres and Planes

**Comment by amirhosseinak20** [comment]
Box

**Comment by codynova** [comment]
Ah, then that's definitely the issue, unfortunately you'll have to switch to a Plane or some other implementation
