### ISSUE TITLE
module not found when using webpack

### ISSUE THREAD

**Issue by amirhosseinak20** [react-spring/cannon-es#37]
after i upgraded my cannon-es to 0.11.0 i face this error:

ERROR in ./node_modules/cannon-es/dist/cannon-es.js
Module not found: Error: Can't resolve 'perf_hooks' in '/mnt/c/Projects/game/node_modules/cannon-es/dist'     @ ./node_modules/cannon-es/dist/cannon-es.js 12202:16-37
 @ ./src/server/game/game/Scene.ts
 @ ./src/server/game/game/Renderer.ts
 @ ./src/server/game/game/index.ts
 @ ./src/view/app.ts
 @ ./src/view/index.ts

here is my webpack config file

`
/* eslint-disable */
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const { ProvidePlugin, HotModuleReplacementPlugin } = require("webpack");
require("dotenv").config({ path: __dirname + "/.env" });

module.exports = (env) => {
  return {
    mode: "development",
    entry: "./src/view/index.ts",
    devtool: "inline-source-map",
    devServer: {
      contentBase: "./dist/view",
      port: process.env.WEBPACK_PORT,
      open: false,
      hot: true,
    },
    plugins: [
      new CleanWebpackPlugin(),
      new HtmlWebpackPlugin({
        template: "public/index.html",
        inject: "body",
        minify: {
          html5: true,
          removeComments: true,
          collapseWhitespace: true,
        },
        templateParameters: {
          PUBLIC_URL: "",
        },
      }),
      new CopyWebpackPlugin([
        {
          from: "public",
          ignore: ["index.html"],
        },
      ]),
      new ProvidePlugin({
        jQuery: "jquery",
        $: "jquery",
        _: "lodash",
      }),
      new HotModuleReplacementPlugin({}),
    ],
    output: {
      filename: "static/js/[name].[hash].js",
      chunkFilename: "static/js/[name].[hash].chunk.js",
      path: path.resolve(__dirname, "dist/view"),
      publicPath: "/",
    },
    resolve: {
      extensions: [".tsx", ".ts", ".js"],
    },
    optimization: {
      usedExports: true,
      moduleIds: "hashed",
      runtimeChunk: "single",
      splitChunks: {
        cacheGroups: {
          vendor: {
            test: /[\\/]node_modules[\\/]/,
            name: "vendors",
            chunks: "all",
          },
        },
      },
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          loader: "babel-loader",
          options: {
            presets: ["@babel/preset-env", "@babel/preset-typescript"],
            plugins: ["@babel/plugin-proposal-class-properties"],
          },
        },
        {
          test: /\.css$/i,
          use: ["style-loader", "css-loader"],
        },
        {
          test: /\.(png|svg|jpe?g|gif)$/i,
          loader: "file-loader",
          options: {
            name: "[ext]/[name].[hash].[ext]",
            outputPath: "assets/images",
          },
        },
        {
          test: /\.(woff|woff2|eot|ttf|otf)$/,
          loader: "file-loader",
          options: {
            name: "[ext]/[name].[hash].[ext]",
            outputPath: "assets/fonts",
          },
        },
        {
          test: /\.(gltf|glb|bin)$/,
          use: [
            {
              loader: "file-loader",
              options: {
                name: "[ext]/[name].[hash].[ext]",
                outputPath: "assets/3DModles",
              },
            },
          ],
        },
      ],
    },
  };
};
`

**Comment by codynova** [comment]
This is caused by #35 which was meant to address #23

**Comment by codynova** [comment]
Released fix in `cannon-es@0.12.0`
