### ISSUE TITLE
Heightfields with negative values will fire face normal errors

### ISSUE THREAD

**Issue by rogerscg** [react-spring/cannon-es#45]
To reproduce, change all heightfield data points in the `heightfield.html` demo to -5. You will see 1,000+ errors thrown from `ConvexPolyhedron` when computing convex triangle pillars.

This was also an issue from 2014: https://github.com/schteppe/cannon.js/issues/149

**Comment by rogerscg** [comment]
The failure to collide might just be due to lack of CCD, not a heightfield issue. Removing that part of the issue (though still a big issue).

**Comment by rogerscg** [comment]
I found the issue, which stems from the convex triangle pillar being upside down when the heightfield has a negative value. Will send a PR in the next few minutes.

**Comment by codynova** [comment]
Awesome, great work digging in and hunting down the issue. I'll cut a quick release with your fix.

**Comment by codynova** [comment]
I've published a new version of cannon-es with the fix to heightfields `cannon-es@0.15.1`

**Comment by rogerscg** [comment]
Awesome, thanks for being so responsive.

**Comment by codynova** [comment]
Absolutely, we welcome any further contributions 👍
